name: tugas_akhir_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.1
  get: 4.6.5
  flutter: 
    sdk: flutter
  get_storage: ^2.1.1
  iconly: ^1.0.1
  pull_to_refresh: ^2.0.0
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  zoom_tap_animation: ^1.1.0
  flutter_easyloading: ^3.0.5
  url_launcher: ^6.1.14
  syncfusion_flutter_pdf: ^24.1.41
  path_provider: ^2.1.1
  screenshot: ^2.1.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

