// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdJek-cBDhg5VfLugaJsVa2CDrSHhhnRg',
    appId: '1:206500201738:web:95f1ef2495e9c9a78a66f3',
    messagingSenderId: '206500201738',
    projectId: 'cipuk-packaging',
    authDomain: 'cipuk-packaging.firebaseapp.com',
    storageBucket: 'cipuk-packaging.appspot.com',
    measurementId: 'G-DBTL8N83SM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqXKse7NZa3Cz6jVS-Tg4oZtHxPUt4-PI',
    appId: '1:206500201738:android:d5f4aeb918a142218a66f3',
    messagingSenderId: '206500201738',
    projectId: 'cipuk-packaging',
    storageBucket: 'cipuk-packaging.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTrjON5Z-WdkcVZY02GBZ1_2Ch6eU_8PY',
    appId: '1:206500201738:ios:e15f9492617f53548a66f3',
    messagingSenderId: '206500201738',
    projectId: 'cipuk-packaging',
    storageBucket: 'cipuk-packaging.appspot.com',
    iosClientId: '206500201738-9ijptq8v3ao9nlci81g3vubijp6t6tob.apps.googleusercontent.com',
    iosBundleId: 'com.example.cipukPackaging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTrjON5Z-WdkcVZY02GBZ1_2Ch6eU_8PY',
    appId: '1:206500201738:ios:57d591d5e996a3588a66f3',
    messagingSenderId: '206500201738',
    projectId: 'cipuk-packaging',
    storageBucket: 'cipuk-packaging.appspot.com',
    iosClientId: '206500201738-2vjc3g1r8ta3t84b9tnsl9s2vofv8lp9.apps.googleusercontent.com',
    iosBundleId: 'com.example.cipukPackaging.RunnerTests',
  );
}
